buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.13.0'
    }
}

repositories {
    google()
    mavenCentral()
}

apply plugin: 'com.android.application'

android {
    compileSdkVersion 36
    namespace = 'org.forzaverita.daldic'
    defaultConfig {
        applicationId "org.forzaverita.daldic"
        minSdkVersion 21
        targetSdkVersion 36
        versionCode 25
        versionName "1.25"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    lint {
        abortOnError false
    }

}
dependencies {
    implementation 'androidx.core:core:1.17.0'
}
